### PR TITLE
Solr 5 integration

### LINKED ISSUE #36: Solr 5 support
Solr 5.0.0 is out: http://lucidworks.com/blog/solr-5-0/

It would be great if c.r.solrinstance would support that release at some point.

### PR DESCRIPTION
**Pull request by saily**
This feature branch includes:
- Huge refactoring with a much cleaner buildout recipe.
- Single core support for Apache Solr 3, 4 (fake by using `collection1` core) including it's templates, see #39
- Multi core support for Apache Solr 3, 4 and 5 including it's templates, fixes #36
- Move templates into their folders
- Descrease loglevel to warning in `logging.properties`.
- Added auto download of Solr releases if `solr-location` is not set in recipe, this keeps legacy installations working fine.
- Added parameter to specify Solr version. People will have to add this parameter to their installations.
- Update documentation, add notes to Solr 5 changes (example `solr.EdgeNGramFilterFactory`)

### CODE REVIEW

**Comment by saily** [comment]
Will fix #32 as well.

**Comment by jensens** [comment]
I'am not deep enough into solr configuration and multi-core knowledge to fully get all implications, but this PR looks very clean, feels well thought and a is big step foreward, so +1 for merging it.

**Comment by saily** [comment]
i rebased the whole branch onto master.

**Comment by loechel** [comment]
Hi, I did an review and some manual tests on this recipe. The changes look very clean as as @jensens already mentioned, but I found several issues that should be solved before merging and a release of an 6.0.0 version. 

* as a conf for plone is one of the standard use cases the example of collective.solr sould work out of the box: https://github.com/collective/collective.solr/raw/master/buildout/solr.cfg but this didn't work due to two reasons: no solr-version specified and field type integer is not in default schema.xml. 
* enablePositionIncrements="true" is not supported by Lucence 5.0 anymore, this in template prevents solr form accepting schema.xml for core
* schema reference synonyms.txt but non ist created by default. 
* default-core parameter is not used in Solr 5 case. should be documented. 

By the way, Plone did not work with generated schema as collective.solr.parser fails due to order of definitions in schema.xml

**Comment by loechel** [comment]
I did some fixings on the mentioned problems. Please review and check if that is consitent with intended cleanup (@saily).

**Comment by saily** [comment]
Hi thanks for reviewing. 
- Adjusting the `solr.cfg` of `collective.solr` is another task which may follow this merge. Several things in that file did not work in past, for example `solr-min-ram` and `solr-max-ram` was never implemented. 
- I didn't catch the `enablePositionIncrements` issue, thanks for that.
- There was never a `synonyms.txt` file created out of a template. This was just copied over, which should work in the same behavior now. So implementing a new `synonym.txt` template, target's a new feature which i did not want to implement through this pull, because we're changing a lot anyway.

**Comment by saily** [comment]
Ok, since we copy over all sample data shipped with solr now, the given schema.xml files should always work. There are some new locations (`lang` folder) and naming conventions for `stopwords.txt` but for now we should just ignore the new location and use the old one, people may have customized their templates.

**Pull request merged**
